### ISSUE TITLE
Enforce usage of `--useUnknownInCatchVariables`

### ISSUE THREAD

**Issue by danielnixon** [danielnixon/eslint-plugin-total-functions#409]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-beta/#use-unknown-catch-variables

**Comment by danielnixon** [comment]
Done

**Comment by akdj** [comment]
Hi @danielnixon, 

Since I updated the package, I have eslint error like: `  1:1  error  TypeScript's useUnknownInCatchVariables mode is required  total-functions/require-strict-mode`

However, I don't know how to enable it correctly, my project is already in strict mode.

**Comment by stenzengel** [comment]
Enforcing `--useUnknownInCatchVariables` seems unnecessary and confusing, because `eslint-plugin-total-functions` already enforces "--strict" which already sets  `--useUnknownInCatchVariables` to `true`
https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables

**Comment by danielnixon** [comment]
Good point @stenzengel. For some reason I believed it was like `noUncheckedIndexedAccess` (i.e. separate from `strict`). Hold tight for a fix.

**Comment by danielnixon** [comment]
Fixed in v4.10.1

**Comment by stenzengel** [comment]
It works. Thanks!
